# Generated by Django 5.2.1 on 2025-05-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('employeid', models.AutoField(primary_key=True, serialize=False)),
                ('employename', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('dateofjoining', models.DateTimeField(auto_now_add=True)),
                ('workingproject', models.CharField(max_length=500)),
            ],
        ),
    ]
